name: CI

on: [Phin_development]

jobs:

    build:
    runs-on: ubuntu-18.04
    services:
    postgres:
        image: postgres:10
        env:
        POSTGRES_USER: \${{ secrets.OED_DB_TEST_POSTGRES_USER}}
        POSTGRES_PASSWORD: \${{ secrets.OED_DB_TEST_POSTGRES_PASSWORD}}
        POSTGRES_DB: \${{ secrets.OED_DB_TEST_POSTGRES_DB}}
        ports:
        - 5432:5432
        options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
env:
    OED_DB_USER: \${{ secrets.OED_DB_TEST_OED_DB_USER}}
    OED_DB_PASSWORD: \${{ secrets.OED_DB_TEST_OED_DB_PASSWORD}}
    OED_DB_DATABASE: \${{ secrets.OED_DB_TEST_OED_DB_DATABASE}}
    OED_DB_TEST_DATABASE: \${{ secrets.OED_DB_TEST_OED_DB_TEST_DATABASE}}
    OED_DB_HOST: \${{ secrets.OED_DB_TEST_OED_DB_TEST_OED_DB_HOST}}
    OED_DB_PORT: \${{ secrets.OED_DB_TEST_OED_DB_TEST_OED_DB_OED_DB_PORT}}
    OED_TOKEN_SECRET: \${{ secrets.OED_DB_TEST_OED_TOKEN_SECRET}}
    OED_SERVER_PORT: \${{ secrets.OED_DB_TEST_OED_OED_SERVER_PORT}}
    OED_TEST_SITE_READING_RATE: 00:15:00
    DOCKER_COMPOSE_VERSION: 1.27.4
    POSTGRES_PASSWORD: \${{ secrets.OED_DB_TEST_POSTGRES_PASSWORD}}

steps:
- uses: actions/checkout@v2
- name: Set up Docker Compose
    run: |
    sudo rm /usr/local/bin/docker-compose
    curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-\$(uname -s)-\$(uname -m)" > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin
- name: Install Node.js
    uses: actions/setup-node@v2
    with:
    node-version: '14'
- name: Set up database
    run: |
    psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
    psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
    psql -c 'CREATE EXTENSION IF NOT EXISTS btree_gist;' -U postgres -d travis_ci_test
- name: Run docker-compose for setup
    run: docker-compose run --rm web src/scripts/installOED.sh --nostart
- name: Check source headers
    run: npm run check:header
- name: Check TypeScript annotations
    run: npm run check:typescript
- name: Check internal type consistency
    run: npm run check:types
- name: Lint check
    run: npm run check:lint
- name: Run tests without Docker
    run: npm test
- name: Run tests in Docker
    run: docker-compose run --service-ports --rm web npm test 